=== medwezhatinka/XmlParser/src/MedicineSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://xml.netbeans.org/schema/MedicineSchema"
    xmlns:tns="http://xml.netbeans.org/schema/MedicineSchema"
    elementFormDefault="qualified">
    <xsd:complexType name="Medicament">
        <xsd:sequence>
            <xsd:element name="Name" type="xsd:string"/>
            <xsd:element name="Pharm" nillable="false" type="xsd:string"/>
            <xsd:element name="Group" type="xsd:string"/>
            <xsd:element name="Analog" type="tns:Analogs"/>
            <xsd:element name="Version" type="tns:Version" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="Version">
        <xsd:sequence>
            <xsd:element name="Type" type="tns:MedVersion"/>
            <xsd:element name="Producer" maxOccurs="unbounded" type="tns:Producer"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="Producer">
        <xsd:sequence>
            <xsd:element name="Certificate" type="tns:Certificate"/>
            <xsd:element name="Package" type="tns:Package"/>
            <xsd:element name="Dosage" type="tns:Dosage"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="Certificate">
        <xsd:sequence>
            <xsd:element name="ID" type="tns:SertificateID"/>
            <xsd:element name="DateOfIssue" type="xsd:date"/>
            <xsd:element name="DateOfExpiry" type="xsd:date"/>
            <xsd:element name="Authority" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="Package">
        <xsd:sequence>
            <xsd:element name="Type" type="xsd:string"/>
            <xsd:element name="Count" type="tns:count"/>
            <xsd:element name="Prise" type="tns:prise"/>
            <xsd:element name="CountInPack" type="tns:count"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="Dosage">
        <xsd:sequence>
            <xsd:element name="Dose" type="tns:dose"/>
            <xsd:element name="Reception" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:simpleType name="Analogs">
        <xsd:list itemType="xsd:string"/>
    </xsd:simpleType>
    <xsd:element name="Medicine">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="Medication" maxOccurs="unbounded" type="tns:Medicament"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:simpleType name="MedGroup">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="антибиотики"/>
            <xsd:enumeration value="жаропонижающие"/>
            <xsd:enumeration value="болеутоляющие"/>
            <xsd:enumeration value="витамины"/>
            <xsd:enumeration value="адсорбирующие"/>
            <xsd:enumeration value="антидипресанты"/>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="MedVersion">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="таблетки"/>
            <xsd:enumeration value="капсулы"/>
            <xsd:enumeration value="порошок"/>
            <xsd:enumeration value="капли"/>
            <xsd:enumeration value="драже"/>
            <xsd:enumeration value="ампулы"/>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="SertificateID">
        <xsd:restriction base="xsd:ID">
            <xsd:pattern value="[A-Z]{1}[0-9]{3}[a-zA-Z]*"/>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="count">
        <xsd:restriction base="xsd:int">
        <xsd:minInclusive value="1"/>
        <xsd:maxInclusive value="300"/>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="prise">
        <xsd:restriction base="xsd:decimal">
        <xsd:minExclusive value="0"/>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="dose">
        <xsd:restriction base="xsd:float">
            <xsd:minExclusive value="0"/>
        </xsd:restriction>
    </xsd:simpleType>
</xsd:schema>

=== medwezhatinka/XmlParser/src/MedicineSchema.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : MedicineSchema.xml
    Created on : June 4, 2013, 5:30 PM
    Author     : Alina_Shumel
    Description:
        Purpose of the document follows.
-->

<ns0:Medicine  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
               xmlns:ns0='http://xml.netbeans.org/schema/MedicineSchema'
               xsi:schemaLocation='http://xml.netbeans.org/schema/MedicineSchema MedicineSchema.xsd'>
    <ns0:Medication>
        <ns0:Name>Азитромицин</ns0:Name>
        <ns0:Pharm>Плива</ns0:Pharm>
        <ns0:Group>антибиотики</ns0:Group>
        <ns0:Analog>Сумамед Азивок Зитроцин Хемомицин</ns0:Analog>
        <ns0:Version>
            <ns0:Type>таблетки</ns0:Type>
            <ns0:Producer>
                <ns0:Certificate>
                    <ns0:ID>A002st</ns0:ID>
                    <ns0:DateOfIssue>2000-03-14</ns0:DateOfIssue>
                    <ns0:DateOfExpiry>2020-03-13</ns0:DateOfExpiry>
                    <ns0:Authority>Institution1</ns0:Authority>
                </ns0:Certificate>
                <ns0:Package>
                    <ns0:Type>блистер</ns0:Type>
                    <ns0:Count>3</ns0:Count>
                    <ns0:Prise>25000</ns0:Prise>
                    <ns0:CountInPack>1</ns0:CountInPack>
                </ns0:Package>
                <ns0:Dosage>
                    <ns0:Dose>0.5</ns0:Dose>
                    <ns0:Reception>1 раз в день, продолжительность лечения 5 дней</ns0:Reception>
                </ns0:Dosage>
            </ns0:Producer>
            <ns0:Producer>
                <ns0:Certificate>
                    <ns0:ID>A002</ns0:ID>
                    <ns0:DateOfIssue>2002-03-14</ns0:DateOfIssue>
                    <ns0:DateOfExpiry>2022-03-13</ns0:DateOfExpiry>
                    <ns0:Authority>Institution1</ns0:Authority>
                </ns0:Certificate>
                <ns0:Package>
                    <ns0:Type>блистер</ns0:Type>
                    <ns0:Count>6</ns0:Count>
                    <ns0:Prise>50000</ns0:Prise>
                    <ns0:CountInPack>1</ns0:CountInPack>
                </ns0:Package>
                <ns0:Dosage>
                    <ns0:Dose>0.125</ns0:Dose>
                    <ns0:Reception>не знаю</ns0:Reception>
                </ns0:Dosage>
            </ns0:Producer>
        </ns0:Version>
        <ns0:Version>
            <ns0:Type>капсулы</ns0:Type>
            <ns0:Producer>
                <ns0:Certificate>
                    <ns0:ID>B345</ns0:ID>
                    <ns0:DateOfIssue>2001-12-12</ns0:DateOfIssue>
                    <ns0:DateOfExpiry>2015-02-12</ns0:DateOfExpiry>
                    <ns0:Authority>Institution2</ns0:Authority>
                </ns0:Certificate>
                <ns0:Package>
                    <ns0:Type>блистер</ns0:Type>
                    <ns0:Count>6</ns0:Count>
                    <ns0:Prise>60500</ns0:Prise>
                    <ns0:CountInPack>1</ns0:CountInPack>
                </ns0:Package>
                <ns0:Dosage>
                    <ns0:Dose>0.25</ns0:Dose>
                    <ns0:Reception>как угодно</ns0:Reception>
                </ns0:Dosage>
            </ns0:Producer>
        </ns0:Version>
    </ns0:Medication>
    <ns0:Medication>
        <ns0:Name>Аскорбиновая кислота</ns0:Name>
        <ns0:Pharm>Борисовский завод мед препаратов</ns0:Pharm>
        <ns0:Group>витамины</ns0:Group>
        <ns0:Analog>Аскорбин Аскорбит Аскорвит Кантан Кантаксин Цебион Целин Лароскорбин Редоксон Скорбумин Вицин Витаскорбол Биовиталь Целаксон Упсавит</ns0:Analog>
        <ns0:Version>
            <ns0:Type>порошок</ns0:Type>
            <ns0:Producer>
                <ns0:Certificate>
                    <ns0:ID>B123</ns0:ID>
                    <ns0:DateOfIssue>1990-03-03</ns0:DateOfIssue>
                    <ns0:DateOfExpiry>2020-03-03</ns0:DateOfExpiry>
                    <ns0:Authority>Минздрав</ns0:Authority>
                </ns0:Certificate>
                <ns0:Package>
                    <ns0:Type>пакетики</ns0:Type>
                    <ns0:Count>1</ns0:Count>
                    <ns0:Prise>2000</ns0:Prise>
                    <ns0:CountInPack>10</ns0:CountInPack>
                </ns0:Package>
                <ns0:Dosage>
                    <ns0:Dose>2</ns0:Dose>
                    <ns0:Reception>2 раза в день</ns0:Reception>
                </ns0:Dosage>
            </ns0:Producer>
        </ns0:Version>
    </ns0:Medication>
   </ns0:Medicine>

=== medwezhatinka/XmlParser/src/MedicineSchema_1.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : MedicineSchema.xml
    Created on : June 4, 2013, 5:30 PM
    Author     : Alina_Shumel
    Description:
        Purpose of the document follows.
-->

<Medicine  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
               xmlns='http://xml.netbeans.org/schema/MedicineSchema'
               xsi:schemaLocation='http://xml.netbeans.org/schema/MedicineSchema MedicineSchema.xsd'>
    <Medication>
        <Name>Азитромицин</Name>
        <Pharm>Плива</Pharm>
        <Group>антибиотики</Group>
        <Analog>Сумамед Азивок Зитроцин Хемомицин</Analog>
        <Version>
            <Type>таблетки</Type>
            <Producer>
                <Certificate>
                    <ID>A002st</ID>
                    <DateOfIssue>2000-03-14</DateOfIssue>
                    <DateOfExpiry>2020-03-13</DateOfExpiry>
                    <Authority>Institution1</Authority>
                </Certificate>
                <Package>
                    <Type>блистер</Type>
                    <Count>3</Count>
                    <Prise>25000</Prise>
                    <CountInPack>1</CountInPack>
                </Package>
                <Dosage>
                    <Dose>0.5</Dose>
                    <Reception>1 раз в день, продолжительность лечения 5 дней</Reception>
                </Dosage>
            </Producer>
            <Producer>
                <Certificate>
                    <ID>A002</ID>
                    <DateOfIssue>2002-03-14</DateOfIssue>
                    <DateOfExpiry>2022-03-13</DateOfExpiry>
                    <Authority>Institution1</Authority>
                </Certificate>
                <Package>
                    <Type>блистер</Type>
                    <Count>6</Count>
                    <Prise>50000</Prise>
                    <CountInPack>1</CountInPack>
                </Package>
                <Dosage>
                    <Dose>0.125</Dose>
                    <Reception>не знаю</Reception>
                </Dosage>
            </Producer>
        </Version>
        <Version>
            <Type>капсулы</Type>
            <Producer>
                <Certificate>
                    <ID>B345</ID>
                    <DateOfIssue>2001-12-12</DateOfIssue>
                    <DateOfExpiry>2015-02-12</DateOfExpiry>
                    <Authority>Institution2</Authority>
                </Certificate>
                <Package>
                    <Type>блистер</Type>
                    <Count>6</Count>
                    <Prise>60500</Prise>
                    <CountInPack>1</CountInPack>
                </Package>
                <Dosage>
                    <Dose>0.25</Dose>
                    <Reception>как угодно</Reception>
                </Dosage>
            </Producer>
        </Version>
    </Medication>
    <Medication>
        <Name>Аскорбиновая кислота</Name>
        <Pharm>Борисовский завод мед препаратов</Pharm>
        <Group>витамины</Group>
        <Analog>Аскорбин Аскорбит Аскорвит Кантан Кантаксин Цебион Целин Лароскорбин Редоксон Скорбумин Вицин Витаскорбол Биовиталь Целаксон Упсавит</Analog>
        <Version>
            <Type>порошок</Type>
            <Producer>
                <Certificate>
                    <ID>B123</ID>
                    <DateOfIssue>1990-03-03</DateOfIssue>
                    <DateOfExpiry>2020-03-03</DateOfExpiry>
                    <Authority>Минздрав</Authority>
                </Certificate>
                <Package>
                    <Type>пакетик</Type>
                    <Count>1</Count>
                    <Prise>2000</Prise>
                    <CountInPack>10</CountInPack>
                </Package>
                <Dosage>
                    <Dose>2</Dose>
                    <Reception>2 раза в день</Reception>
                </Dosage>
            </Producer>
        </Version>
    </Medication>
   </Medicine>

=== medwezhatinka/XmlParser/xml/MedicineSchema2.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : MedicineSchema2.xml
    Created on : June 4, 2013, 4:16 PM
    Author     : Alina_Shumel
    Description:
        Purpose of the document follows.
-->

<ns0:Medicine  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
               xmlns:ns0='http://xml.netbeans.org/schema/MedicineSchema'
               xsi:schemaLocation='http://xml.netbeans.org/schema/MedicineSchema MedicineSchema.xsd'>
    <ns0:Medication>
        <ns0:Name>Азитромицин</ns0:Name>
        <ns0:Pharm>РБ</ns0:Pharm>
        <ns0:Group>антибиотики</ns0:Group>
        <ns0:Analog>хрень [htym2 [htym3</ns0:Analog>
        <ns0:Version>
            <ns0:Type>таблетки</ns0:Type>
            <ns0:Producer>
                <ns0:Certificate>
                    <ns0:ID>A001</ns0:ID>
                    <ns0:DateOfIssue>2001-12-12</ns0:DateOfIssue>
                    <ns0:DateOfExpiry>2015-01-12</ns0:DateOfExpiry>
                    <ns0:Authority>Не знаю</ns0:Authority>
                </ns0:Certificate>
                <ns0:Package>
                    <ns0:Type>блистер</ns0:Type>
                    <ns0:Count>10</ns0:Count>
                    <ns0:Prise>3000</ns0:Prise>
                    <ns0:CountInPack>1</ns0:CountInPack>
                </ns0:Package>
                <ns0:Dosage>
                    <ns0:Dose>0.04</ns0:Dose>
                    <ns0:Reception>каждые 6 часов</ns0:Reception>
                </ns0:Dosage>
            </ns0:Producer>
        </ns0:Version>
    </ns0:Medication>

</ns0:Medicine>
